name: ci

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - run: pip install -r requirements.txt
      - name: execute py script # run the run.py to get the latest data
        run: |
          python generate-cooccurrence-data.py
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'network-app'
          destination-github-username: 'kallewesterling'
          destination-repository-name: 'drag-network'
          user-email: kwesterling1@gradcenter.cuny.edu
          target-branch: main
